---
name: Unit Tests for S3GW UI
on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout S3GW UI
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Run Unit Tests
        run: |
          npm run test:ci
