---
name: Lint & Unit Tests for S3GW UI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout S3GW UI
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout S3GW UI
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test:ci
